// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/toast/ToastA.tsx": () => import("../components/mockups/toast/ToastA.tsx"),
  "./components/mockups/toast/ToastB.tsx": () => import("../components/mockups/toast/ToastB.tsx"),
  "./components/mockups/toast/ToastC.tsx": () => import("../components/mockups/toast/ToastC.tsx"),
  "./components/mockups/plan-drawer/CardCTA.tsx": () => import("../components/mockups/plan-drawer/CardCTA.tsx"),
  "./components/mockups/plan-drawer/Inline.tsx": () => import("../components/mockups/plan-drawer/Inline.tsx"),
  "./components/mockups/plan-drawer/Row.tsx": () => import("../components/mockups/plan-drawer/Row.tsx")
};
